# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 999
    target-branch: 'beta'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 999
    target-branch: 'stable'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 999
    target-branch: 'beta'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
    groups:
      typescript:
        patterns:
          - '@types/*'
          - 'typescript'
      code-management:
        patterns:
          - 'prettier'
          - '@demosjarco/prettier-config'
          - 'eslint'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 999
    target-branch: 'stable'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
    groups:
      typescript:
        patterns:
          - '@types/*'
          - 'typescript'
      code-management:
        patterns:
          - 'prettier'
          - '@demosjarco/prettier-config'
          - 'eslint'
