name: Compile

on:
  push:
    paths:
      - '.github/workflows/compile.yml'
      - 'src/**'
      - 'package*.json'
      - 'tsconfig.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          disable-sudo: true
          egress-policy: audit
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version: lts/*
          check-latest: true
          cache: npm
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - uses: actions/cache/restore@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: |
            .tsbuildinfo
            dist
          # npm packages + tsconfig + value of `include` in tsconfig
          key: typescript-cache-tsc-${{ hashFiles('**/*.tsbuildinfo') }}
          restore-keys: |
            typescript-cache-tsc-
          enableCrossOsArchive: true
      - run: npm run build
      - uses: actions/cache/save@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: |
            .tsbuildinfo
            dist
          # npm packages + tsconfig + value of `include` in tsconfig
          key: typescript-cache-tsc-${{ hashFiles('**/*.tsbuildinfo') }}
          enableCrossOsArchive: true
      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: dist
          path: ${{ github.workspace }}/dist
          if-no-files-found: error
