name: Delete Release

on:
  release:
    types:
      - deleted

permissions:
  contents: read

jobs:
  manage-npm-version:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          disable-sudo: true
          egress-policy: audit
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - run: echo "PACKAGE_NAME=$(jq -r '.name' package.json)" >> $GITHUB_OUTPUT
        id: pkg-name
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: lts/*
          check-latest: true
          cache: npm
          registry-url: 'https://registry.npmjs.org'
      - run: npm unpublish ${{ steps.pkg-name.outputs.PACKAGE_NAME }}@"${{ github.event.release.tag_name }}"
        id: unpublish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        continue-on-error: true
      - run: npm deprecate ${{ steps.pkg-name.outputs.PACKAGE_NAME }}@"${{ github.event.release.tag_name }}" "This version has been deprecated due to removal of corresponding GitHub release"
        if: steps.unpublish.outcome == 'failure'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
