name: Publish

on:
  release:
    types:
      - published

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          disable-sudo: true
          egress-policy: audit
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Get Branch Name from Tag
        id: get-branch
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          COMMIT_SHA=$(git rev-list -n 1 $TAG_NAME)
          BRANCH_NAME=$(gh api repos/${{ github.repository }}/commits/$COMMIT_SHA/branches-where-head --jq '.[0].name')
          echo "NPM_TAG::$BRANCH_NAME" >> $GITHUB_OUTPUT
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: lts/*
          check-latest: true
          cache: npm
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish --tag ${{ steps.get-branch.outputs.NPM_TAG }} --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
